# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Active Learning Review
author: Daniel Gissin
email: daniel.gissin (at) mail.huji.ac.il
description: >- # this means to ignore newlines until "baseurl:"
  An introduction to the active learning framework, reviewing current active learning algorithms for deep learning models along with a proposed "Discriminative Active Learning" method. 
baseurl: "/DiscriminativeActiveLearning"
url: "https://dsgissin.github.io/" 
github_username: dsgissin

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
